### PR TITLE
Repair Missing Header for iOS

### PR DESCRIPTION
**Pull request by melj32app**
Compatibility changes for iOS14 as introduced in native iOS SDK 5.3.1.

### CODE REVIEW

**Comment by frankus** [comment]
We probably also need to change the `apptentive-react-native.podspec` file's `apptentive-ios` dependency version to `~>5.3.1` so that it doesn't pull in the 5.3.0 that still has the old header file.

**Comment by weeeBox** [comment]
Sample app verified

@frankus, are you sure using strict optimistic versioning would be a good idea? `~>5.3.1` might exclude future 5.4.x+ versions

**Comment by frankus** [comment]
We need 5.3.1 or later, up to but not including 6.0. Not sure if there's a way to specify that with the syntax: https://guides.cocoapods.org/syntax/podspec.html#dependency

**Comment by frankus** [comment]
Looks like you can comma-separate several of them: https://guides.rubygems.org/patterns/#semantic-versioning, e.g. `">= 5.3.1, < 6.0"`.

**Comment by weeeBox** [comment]
@frankus, the correct syntax is `">= 5.3.1", "< 6.0"`. I've updated the podspec: https://github.com/apptentive/apptentive-react-native/pull/134/commits/b3bce5901fe8cb70d04599124a383275cf40515c

**Review by weeeBox — APPROVED** [review]
🚢 🛳⛴

**Pull request merged**
